version: "3"

services:
  postgres:
    container_name: postgresCheck
    image: postgres:10.6-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=adminasd123!
      - POSTGRES_USER=admin
      - POSTGRES_DB=check
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/posgresql

volumes:
  postgres-data: # Для запуска docker-compose up -d
